### ISSUE TITLE
"/usr/bin/ld: cannot find -lcilkrts" error

### ISSUE THREAD

**Issue by NanXiao** [wmoses/Parallel-IR#70]
Hi,

Greeting from me!

I follow [Quick start](http://cilk.mit.edu/download/#quick-start) to build the `Tapir-LLVM` on `Arch Linux` successfully. Then I write a simple program:  

```
$ cat test.c
#include <stdio.h>
#include <cilk/cilk.h>

int fib(int n) {
  if (n < 2) return n;
  int x, y;
  x = cilk_spawn fib(n - 1);
  y = fib(n - 2);
  cilk_sync;
  return x + y;
}

int main(void)
{
        printf("%d\n", fib(100));
        return 0;
}
```

But it reports a link error:  

```
$ clang -fcilkplus test.c
/usr/bin/ld: cannot find -lcilkrts
clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)
```

After using `-v` option:  

```
$ clang -v -fcilkplus test.c
clang version 5.0.0 (https://github.com/wsmoses/Cilk-Clang 9e81b3be8a7749cb8feea3f6bad30df9b7ba1e75) (https://github.com/wsmoses/Parallel-IR 4ccec4566bf6d847c26c8e8d1af3ec378cc262f5)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/xiaonan/Tapir-Meta/tapir/build/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-pc-linux-gnu/5.4.1
Found candidate GCC installation: /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.1
Found candidate GCC installation: /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1
Found candidate GCC installation: /usr/lib/gcc/x86_64-pc-linux-gnu/8.1.1
Found candidate GCC installation: /usr/lib64/gcc/x86_64-pc-linux-gnu/5.4.1
Found candidate GCC installation: /usr/lib64/gcc/x86_64-pc-linux-gnu/6.4.1
Found candidate GCC installation: /usr/lib64/gcc/x86_64-pc-linux-gnu/7.3.1
Found candidate GCC installation: /usr/lib64/gcc/x86_64-pc-linux-gnu/8.1.1
Selected GCC installation: /usr/lib64/gcc/x86_64-pc-linux-gnu/8.1.1
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
 "/home/xiaonan/Tapir-Meta/tapir/build/bin/clang-5.0" -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name test.c -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -v -dwarf-column-info -debugger-tuning=gdb -resource-dir /home/xiaonan/Tapir-Meta/tapir/build/lib/clang/5.0.0 -internal-isystem /usr/local/include -internal-isystem /home/xiaonan/Tapir-Meta/tapir/build/lib/clang/5.0.0/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdebug-compilation-dir /home/xiaonan -ferror-limit 19 -fmessage-length 121 -fcilkplus -fobjc-runtime=gcc -fdiagnostics-show-option -fcolor-diagnostics -o /tmp/test-1711bf.o -x c test.c
clang -cc1 version 5.0.0 based upon LLVM 5.0.0git-4ccec4566bf default target x86_64-unknown-linux-gnu
ignoring nonexistent directory "/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/include
 /home/xiaonan/Tapir-Meta/tapir/build/lib/clang/5.0.0/include
 /usr/include
End of search list.
 "/usr/bin/ld" --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o a.out /usr/lib64/gcc/x86_64-pc-linux-gnu/8.1.1/../../../../lib64/crt1.o /usr/lib64/gcc/x86_64-pc-linux-gnu/8.1.1/../../../../lib64/crti.o /usr/lib64/gcc/x86_64-pc-linux-gnu/8.1.1/crtbegin.o -L/usr/lib64/gcc/x86_64-pc-linux-gnu/8.1.1 -L/usr/lib64/gcc/x86_64-pc-linux-gnu/8.1.1/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/lib64/gcc/x86_64-pc-linux-gnu/8.1.1/../../.. -L/home/xiaonan/Tapir-Meta/tapir/build/bin/../lib -L/lib -L/usr/lib /tmp/test-1711bf.o -lcilkrts -lgcc --as-needed -lgcc_s --no-as-needed -lc -lgcc --as-needed -lgcc_s --no-as-needed /usr/lib64/gcc/x86_64-pc-linux-gnu/8.1.1/crtend.o /usr/lib64/gcc/x86_64-pc-linux-gnu/8.1.1/../../../../lib64/crtn.o
/usr/bin/ld: cannot find -lcilkrts
clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)
```

There is indeed no `libcilkrts` in the `lib` directory:

```
$ ls /home/xiaonan/Tapir-Meta/tapir/build/bin/../lib/libci*
ls: cannot access '/home/xiaonan/Tapir-Meta/tapir/build/bin/../lib/libci*': No such file or directory
```

Does I miss something? Thanks very much in advance!

Best Regards
Nan Xiao

**Comment by VictorYing** [comment]
LLVM/Clang projects and derivatives including Tapir do not come bundled with any version of libcilkrts. They instead rely on you having one already available somewhere on your system. The lack of mention of this seems like a bug in the quick start guide. The guide as currently presented only works if your OS distro version was released in the right window of time to come with the right version of GCC as the system compiler resulting in a version of libcilkrts sitting in the default runtime library search path (probably in /usr/lib/), i.e., the system compiler was a version of GCC between whenever they added Cilk support around 4.9 or 5.0, and whenever they're taking out Cilk support (8.x?). I know from experience that this means the quick start guide has been broken for users still on Ubuntu LTS 14.04 (comes with GCC 4.8 as the system compiler, and is still a year away from EOL) as well as increasingly on newer releases over time. For these systems, you need to make the runtime linker search somewhere else for a version of libcilkrts, e.g., by pointing the runtime linker to the libraries of a version of GCC in the requisite window, for example:

- adding `${path to GCC between 5.x and 7.x}/lib64` to your `LD_LIBRARY_PATH`,
- adding `-Wl,-rpath=${path to GCC between 5.x and 7.x}/lib64` as a command-line argument every time you invoke Clang to link an executable, or
- adding `-DCMAKE_CXX_LINK_FLAGS="-Wl,-rpath=${path to GCC between 5.x and 7.x}/lib64"` to the command-line arguments you give CMake when setting up your Tapir/LLVM/Clang build, which has the same effect as the previous. I would strongly advise this option be added to the quick start guide, since it's a set-once-and-forget step that won't lead to breakage and confusion when you forget about it and then move between shell environments.

**Comment by neboat** [comment]
Hi Nan,

Thanks for giving Tapir a try.

As @YingVictor mentioned, Tapir/LLVM does not come bundled with a copy of libcilkrts, and we've been relying on separate installations of that library.  I'm not sure if Arch packages libcilkrts, but you can build libcilkrts from source using Tapir/LLVM.  (To build libcilkrts you do need a Cilk compiler, such as Tapir/LLVM or one of the versions of GCC that @YingVictor mentioned.)

Here is a copy of the source for libcilkrts with build instructions that should work with Tapir/LLVM: https://github.com/CilkHub/cilkrts.  We've tested that copy of libcilkrts on a few Linux distributions as well as Mac OS X, but I don't think we've tested it on Arch.  Please let us know whether that works for you.

Cheers,
TB

**Comment by NanXiao** [comment]
@YingVictor @neboat ,

Firstly, thanks very much for your kind help and time!

Yes, after installing [https://github.com/CilkHub/cilkrts](https://github.com/CilkHub/cilkrts), now I can build successfully.  

Maybe a dumb question, why don't include [https://github.com/CilkHub/cilkrts](https://github.com/CilkHub/cilkrts) into `Tapir-LLVM`? For license issue? Or just keep `Tapir-LLVM` clean? Per my understanding, since `Tapir-LLVM` is used to build `cilk` related programs, provide a out-of-box library is better.

Thanks very much again!

Best Regards
Nan Xiao

**Comment by wsmoses** [comment]
Hi Nan,

Often users will find that they already have a version of the Cilk runtime installed (for instance on ubuntu the libcilkrts package comes with gcc). Likewise, the Cilk runtime isn't a dependency for Tapir to run, which lets the two projects be decoupled into two packages (potentially saving a bit of headache about having one large package where all you need is a specific component).

That said I agree some of the default installation methods should be updated to reflect installing the cilkruntime and we can do so shortly!

Cheers,
Billy
